Added new step to get new packages

diff --git a/.github/workflows/magma-build-3rd-party.yml b/.github/workflows/magma-build-3rd-party.yml
--- a/.github/workflows/magma-build-3rd-party.yml
+++ b/.github/workflows/magma-build-3rd-party.yml
@@ -19,6 +19,7 @@ on:
     branches:
       - master
       - 'v1.*'
+      - feature/packages_missing
     paths:
       - third_party/**
       - .github/workflows/magma-build-3rd-party.yml
@@ -113,3 +114,27 @@ jobs:
             --detailed-summary \
             --target-props="deb.component=main;deb.distribution=${{ env.distribution }};deb.architecture=${architecture}" \
             "(*${{ matrix.dependency }}*).deb" ${{ env.repository }}/pool/${{ env.distribution }}/{1}.deb
+
+      - name: Download and upload missed Debian packages
+        run: |
+          
+          packages=("libsystemd-dev" "getenvoy-envoy" "td-agent-bit" "libczmq-dev")
+          
+          # Update the package list
+          sudo apt-get update
+          
+          # Download each package and upload to JFrog
+          for package in "${packages[@]}"; do
+              sudo apt-get download "$package"
+              
+              # Attempt to upload the downloaded package to JFrog
+              deb_file="${package}_*.deb" # Assumes the downloaded file will follow this naming pattern
+              jf rt upload \
+                  --recursive=false \
+                  --detailed-summary \
+                  --target-props="deb.component=main;deb.distribution=${{ env.distribution }};" \
+                  "$deb_file" "${{ env.repository }}/pool/${{ env.distribution }}/" || echo "Warning: Failed to upload $deb_file for package $package."
+          done
+          
+          # List the downloaded packages
+          ls
